# Generated by Django 4.2.1 on 2023-06-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0002_post_delete_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created",
        ),
    ]
