# Generated by Django 4.2 on 2023-06-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notice", "0003_rename_created_at_post_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.CharField(max_length=15),
        ),
    ]
