# Generated by Django 4.2 on 2023-06-27 18:27

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="fireVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="C:\\Users\\User\\Desktop\\Big\\Big\\media"
                        ),
                        upload_to="fire/",
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
