# Generated by Django 4.2.2 on 2023-06-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="pw",
            field=models.CharField(max_length=1000),
        ),
    ]
