# Generated by Django 4.2 on 2023-06-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_user_pw"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="KT사원", max_length=15),
        ),
    ]
