# Generated by Django 4.2 on 2023-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="locked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
