# Generated by Django 4.2.2 on 2023-06-13 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("login", "0002_alter_user_pw"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                ("borad_id", models.IntegerField(primary_key=True, serialize=False)),
                ("day", models.DateField()),
                ("in_time", models.DateTimeField()),
                ("out_time", models.DateTimeField()),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("work_type", models.CharField(max_length=255)),
                ("contents", models.CharField(max_length=255)),
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="login.user"
                    ),
                ),
            ],
        ),
    ]
