# Generated by Django 4.2.2 on 2023-06-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workLog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="borad_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
