# Generated by Django 4.2.2 on 2023-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workLog", "0004_rename_user_id_worklog_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="end",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="start",
            field=models.DateField(),
        ),
    ]
