# Generated by Django 4.2.2 on 2023-06-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workLog", "0006_rename_borad_id_worklog_board_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="end",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="in_time",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="out_time",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="start",
            field=models.CharField(max_length=255),
        ),
    ]
