# Generated by Django 4.2 on 2023-06-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workLog", "0009_worklog_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="worklog",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="worklog",
            name="region",
            field=models.CharField(default="", max_length=50),
        ),
    ]
