# Generated by Django 4.2 on 2023-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workLog", "0011_alter_worklog_end_alter_worklog_in_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="in_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="out_time",
            field=models.DateTimeField(),
        ),
    ]
