# Generated by Django 4.2 on 2023-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workLog", "0012_alter_worklog_in_time_alter_worklog_out_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="worklog",
            name="in_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="worklog",
            name="out_time",
            field=models.TimeField(),
        ),
    ]
